<?php
require_once '../../../users/init.php';
require_once $abs_us_root.$us_url_root.'users/includes/template/prep.php';

//Do not edit this file! Take the code snippets and make your own :)
if(!hasPerm([2],$user->data()->id)){
  die("insufficient permissions");
}
if(!pluginActive("watchdog",true)){
  die("plugin is not active");
}


?>
<div class="row">
  <div class="col-12 text-center">
    <h1>Example Function Calls</h1>
    <p>These are only simple examples so you can implement these features with your own design.</p>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <h2 class="">Users Online Status (Updates Every 20 Seconds)</h2>
    See the javascript at the bottom of this page to see how it's done
  </div>
</div>
<div class="row" id="onlineHere">

</div>
<br><br>

<div class="row">
  <div class="col-12">
    <h2 class="">Is User Online?</h2>
    This is function <b>isUserOnline($id,$multiple = 4)</b>
    <br>
    <p>Are YOU online?  <?php
    bin(isUserOnline($user->data()->id));
    //bin is just a function that echoes a green yes or a red no
    ?></p>
  </div>
</div>
<br>
<div class="row">
  <div class="col-12">
    <h2>Fetch Popular Pages</h2>
    This is function <b>fetchPopularPages($count = 20)</b>
    <p>A dwell hit is every time a user or guest reports in on a particular page. The page MUST be in the UserSpice database.</p>

  </div>
</div>
<div class="row">
  <?php
  $pages = fetchPopularPages();

  foreach($pages as $p){ ?>
    <div class="col-12 col-sm-4" style="padding-top:25px; background-color:lightgray; border:1px solid black; margin: 25px;">
      <h5><b>
        <?php
        echo $p->page;
        if($p->title != ""){
          echo " - ".$p->title;
        }
        ?>
      </b></h5>
      <br>
      <h3>
        <span style="color:red;"><b><?=$p->dwells?></b></span>
          Dwell Hits
      </h3>

    </div>
  <?php } ?>
</div>
<br>
<div class="row">
  <div class="col-12">
    <h2>Online Users By Page</h2>
    This is function <b>fetchOnlineUserLocations($multiple = 4)</b><br>
    Shows you not only who is on your site, but where they are.<br><br>

  </div>
</div>
<div class="row">
  <?php
  $pages = fetchOnlineUserLocations();
  foreach($pages as $p){ ?>
    <div class="col-12 col-sm-3" style="padding-top:25px; padding-bottom:25px; background-color:lightblue; border:1px solid blue; margin: 25px;">
      <h5 class="text-center"><?=$p->page?></h5>
      <?php foreach($p->users as $u){ ?>
        <a href="<?=$us_url_root?>users/admin.php?view=user&id=<?=$u?>"><?=echouser($u)?></a><br>
      <?php } ?>
    </div>
  <?php } ?>
</div>
<br>

<script type="text/javascript">
$(document).ready(function() {
function onlineReport(){
  console.log("requesting");
  var formData = {
    'request' 	     : "usersWithOnlineStatus",
    'offline_after'  : 120, //how many seconds without a checkin before we consider them offline
  };

  $.ajax({
    type 		: 'POST',
    url 		: '<?=$us_url_root?>usersc/plugins/watchdog/sample_parser.php',
    data 		: formData,
    dataType 	: 'json',
  })

  .done(function(data) {
    console.log(data);
    $("#onlineHere").html(data.data);
  })
}

onlineReport();
setInterval(onlineReport,20000);
});
</script>



<?php
require_once $abs_us_root . $us_url_root . 'users/includes/html_footer.php';
